### PR TITLE
LICENSE: was missing the holder name

### PR DESCRIPTION
**Pull request by vbatts**
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

### CODE REVIEW

**Comment by vbatts** [comment]
cc @caniszczyk

**Comment by caniszczyk** [comment]
That's just the template, no need to add this to the actual LICENSE :)

**Comment by mikebrow** [comment]
yeah... sort of messed up the model from earlier revisions where people would edit the copyright notice after the "end of terms" section.. and leave it in a directory to indicate it applies to stuff in the directory and below ... now it's got an appendix and people don't edit it.

**Comment by vbatts** [comment]
On 09/01/20 12:33 -0800, Chris Aniszczyk wrote:
>   That's just the template, no need to add this to the actual LICENSE :)

oh fair

**Comment by mikebrow** [comment]
course we have this issue across the various open containers projects...

**Pull request closed without merging**
